dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - smartcontractkit/chainlink@1.0.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"
      - "@chainlink=smartcontractkit/chainlink@1.0.1"
dotenv: .env
wallet:
  private_key: ${PRIVATE_KEY
networks:
  kovan:
    verify: True
    weth_token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
